Update seraphscript

diff --git a/seraphscript b/seraphscript
--- a/seraphscript
+++ b/seraphscript
@@ -1,1 +1,78 @@
+# SERAPH
+#!/bin/bash
+cd ..
+# Check for systemd
+systemctl --version >/dev/null 2>&1 || { echo "systemd is required. Are you using Ubuntu 16.04?"  >&2; exit 1; }
+echo && sleep 3
+# Gather input from user
+read -e -p "Masternode Private Key (e.g. 7edfjLCUzGczZi3JQw8GHp434R9kNY33eFyMGeKRymkB56G4324h) : " key
+if [[ "$key" == "" ]]; then
+    echo "WARNING: No private key entered, exiting!!!"
+    echo && exit
+fi
+sleep 3
+read -e -p "Add swap space? (Recommended) [Y/n] : " add_swap
+if [[ ("$add_swap" == "y" || "$add_swap" == "Y" || "$add_swap" == "") ]]; then
+    read -e -p "Swap Size [2G] : " swap_size
+    if [[ "$swap_size" == "" ]]; then
+        swap_size="2G"
+    fi
+fi    
+# Add swap if needed
+if [[ ("$add_swap" == "y" || "$add_swap" == "Y" || "$add_swap" == "") ]]; then
+    if [ ! -f /swapfile ]; then
+        echo && echo "Adding some swap space..."
+        sleep 3
+        sudo fallocate -l $swap_size /swapfile
+        sudo chmod 600 /swapfile
+        sudo mkswap /swapfile
+        sudo swapon /swapfile
+        echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
+        sudo sysctl vm.swappiness=10
+        sudo sysctl vm.vfs_cache_pressure=50
+        echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf
+        echo 'vm.vfs_cache_pressure=50' | sudo tee -a /etc/sysctl.conf
+    else
+        echo && echo "Swap file detected, we don't need it- skipping the swap!"
+        sleep 3
+    fi
+fi
+
+sudo apt-get update -y
+sudo apt-get upgrade -y
+sudo apt-get dist-upgrade -y
+sudo apt-get install nano htop git -y
+sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils software-properties-common -y
+sudo apt-get install libboost-all-dev -y
+sudo apt-get install libzmq3-dev libminiupnpc-dev libssl-dev libevent-dev -y
+sudo add-apt-repository ppa:bitcoin/bitcoin -y
+sudo apt-get update -y
+sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
+
+git clone https://github.com/seraphcoin/seraph.git
+cd ~/seraph
+chmod 755 autogen.sh
+./autogen.sh
+./configure
+chmod 755 share/genbuild.sh
+make
+cd src
+./seraphd -daemon
+sleep 10
+
+#  read -p " > Enter rpcuser : " rpcuser
+#  echo
+#  read -p " > Eneter rpcpassword : " rpcpassword
+#  echo
+
+rpcuser=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
+rpcpassword=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
+externalip=$(hostname -i | awk '{print $2}')
+#masternodekey=$(./seraph-cli masternode genkey)
+./seraph-cli stop
+echo -e "rpcuser=$rpcuser\nrpcpassword=$rpcpassword\nrpcallowip=127.0.0.1\nlisten=1\nserver=1\ndaemon=1\nrpcport=25674\nstaking=0\nexternalip=$externalip:25676\nmaxconnections=256\nmasternode=1\nmasternodeprivkey=$key" >> $HOME/.seraph/seraph.conf
+echo "Masternode private key: $key"
+./seraphd -daemon
+
+echo "Masternode private key: $key"
 
